### ISSUE TITLE
가끔 토스트가 가려지는 오류가 있습니다.

### ISSUE THREAD

**Issue by RePerPM** [MapleKuroXNeko/SimAlba#2]
개선이 가능하면 부탁드립니다ㅠㅠ
진짜 혁신적인 프로그램이라 너무 고맙습니당.

**Comment by MapleKuroxNeko** [comment]
토스트는 다른 라이브러리를 사용하고 있어서 변경하는게 아니라면 제가 수정하기 어렵습니다.
